name: Auto Commit

on:
  schedule:
    - cron: "*/15 * * * *"

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Auto-commit changes
        run: |         
          git add .
          git commit -m "Automated commit [skip ci]" || exit 0
          git push
